"""
ComfyUI Local JSON Extractor (llama.cpp)
MIT License
"""

from .node_llama_json_extractor import NODE_CLASS_MAPPINGS as EXTRACTOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EXTRACTOR_DISPLAY
from .json_parser import NODE_CLASS_MAPPINGS as PARSER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PARSER_DISPLAY
from .safety_gate import NODE_CLASS_MAPPINGS as SAFETY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAFETY_DISPLAY
from .vision_safety_checker import NODE_CLASS_MAPPINGS as VISION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISION_DISPLAY
from .vision_safety_checker_hf import NODE_CLASS_MAPPINGS as VISION_HF_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISION_HF_DISPLAY
from .multidomain_safety_gate import NODE_CLASS_MAPPINGS as MULTIDOMAIN_GATE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MULTIDOMAIN_GATE_DISPLAY
from .nudenet_safety_checker import NODE_CLASS_MAPPINGS as NUDENET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NUDENET_DISPLAY

# Merge all node mappings
NODE_CLASS_MAPPINGS = {**EXTRACTOR_MAPPINGS, **PARSER_MAPPINGS, **SAFETY_MAPPINGS, **VISION_MAPPINGS, **VISION_HF_MAPPINGS, **MULTIDOMAIN_GATE_MAPPINGS, **NUDENET_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**EXTRACTOR_DISPLAY, **PARSER_DISPLAY, **SAFETY_DISPLAY, **VISION_DISPLAY, **VISION_HF_DISPLAY, **MULTIDOMAIN_GATE_DISPLAY, **NUDENET_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
