from .nodes import NODE_CLASS_MAPPINGS as NODES_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY_MAPPINGS
from .safety_checker import NODE_CLASS_MAPPINGS as SAFETY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAFETY_DISPLAY_MAPPINGS
from .output_processor import NODE_CLASS_MAPPINGS as OUTPUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OUTPUT_DISPLAY_MAPPINGS

# Merge all node mappings
NODE_CLASS_MAPPINGS = {**NODES_MAPPINGS, **SAFETY_MAPPINGS, **OUTPUT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODES_DISPLAY_MAPPINGS, **SAFETY_DISPLAY_MAPPINGS, **OUTPUT_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']