"""
ComfyUI BEN2 & BiRefNet Background Removal
Non-GPL alternative using ONNX runtime & transformers
Includes utility nodes for image resizing and memory management
"""

from .ben2_onnx_node import NODE_CLASS_MAPPINGS as BEN2_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BEN2_DISPLAY
from .birefnet_onnx_node import NODE_CLASS_MAPPINGS as BIREFNET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BIREFNET_DISPLAY
from .birefnet_hr_node import NODE_CLASS_MAPPINGS as BIREFNET_HR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BIREFNET_HR_DISPLAY
from .image_resize_nodes import NODE_CLASS_MAPPINGS as RESIZE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESIZE_DISPLAY
from .smart_resize_nodes import NODE_CLASS_MAPPINGS as SMART_RESIZE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SMART_RESIZE_DISPLAY
from .memory_management_nodes import NODE_CLASS_MAPPINGS as MEMORY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MEMORY_DISPLAY

# Merge all node mappings
NODE_CLASS_MAPPINGS = {**BEN2_MAPPINGS, **BIREFNET_MAPPINGS, **BIREFNET_HR_MAPPINGS, **RESIZE_MAPPINGS, **SMART_RESIZE_MAPPINGS, **MEMORY_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BEN2_DISPLAY, **BIREFNET_DISPLAY, **BIREFNET_HR_DISPLAY, **RESIZE_DISPLAY, **SMART_RESIZE_DISPLAY, **MEMORY_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
